cache_enabled: true
embedding_config:
  api_key: ollama
  base_url: http://localhost:11434/v1
  dimensions: null
  model: nomic-embed-text
  provider: ollama
enable_async: true
enable_graph: true
graph_store_config:
  database: neo4j
  password: mem0production
  provider: neo4j
  uri: bolt://localhost:17687
  username: neo4j
llm_config:
  api_key: ollama
  base_url: http://localhost:11434/v1
  max_tokens: 2000
  model: llama3.2:3b
  provider: ollama
  temperature: 0.7
memory_provider: both
redis_url: redis://:mem0redis@localhost:16379
vector_store_config:
  api_key: null
  collection_name: mem0_collection
  host: localhost
  port: 16333
  provider: qdrant
